/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplicationbelajar;

import java.awt.*;
import java.sql.*;
import java.util.*;
import javax.swing.*;
import javax.swing.table.*;
import java.lang.Object;
import static java.lang.Thread.sleep;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author linux
 */
public class peminjaman extends javax.swing.JFrame {

    private Connection con;
    private void StatusDB(){
        try{
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_perpustakaan_ak","root","");
            status1.setForeground(Color.green);
            status1.setText("Connected");
        }catch(ClassNotFoundException | SQLException e){
            status1.setForeground(Color.red);
            status1.setText("Disconnected");
            JOptionPane.showMessageDialog(null, "ERORR\nAnda tidak terhubung ke Database, silahkan cek port MySql atau aktifkan aplikasi MySql.\nDefault port : 3306");
            System.exit(0);
        }
    }
    /**
     * Creates new form peminjaman
     */
    public peminjaman() {
        initComponents();
        this.setLocationRelativeTo(null);
        getCalender();
        StatusDB();
        Show_User_In_JTable();
    }
    public void getCalender(){
        Calendar cal = new GregorianCalendar();
        int hari = cal.get(Calendar.DAY_OF_MONTH);
        int bulan = cal.get(Calendar.MONTH);
        int tahun = cal.get(Calendar.YEAR);
        tgl.setText(tahun + "-" + (bulan+1) + "-" + hari);
        status.setText(tahun + "-" + (bulan+1) + "-" + hari);
    }
    public Connection getConnection(){
        Connection con;
        try{
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_perpustakaan_ak","root","");
            return con;
        }catch(ClassNotFoundException | SQLException e){
            
            JOptionPane.showMessageDialog(null, "ERORR\nAnda tidak terhubung ke Database, silahkan cek port MySql atau aktifkan aplikasi MySql.\nDefault port : 3306");
            System.exit(0);
        }
        return null;
    }
    public ArrayList<User> getUserList(){
        ArrayList<User> userList = new ArrayList<User>();
        con = getConnection();
        String query = "SELECT * FROM `tb_pinjam`";
        Statement st;
        ResultSet rs;
        try{
            st = con.createStatement();
            rs = st.executeQuery(query);
            User user;
            while(rs.next()){
                user = new User(rs.getInt("no"),rs.getInt("kode_buku"),rs.getString("buku"),rs.getString("tgl_pinjam"),rs.getString("tgl_kembali"),rs.getString("status"),rs.getInt("nis"));
                userList.add(user);
            }
        }catch(Exception ex){
            ex.printStackTrace();
        }
        return userList;
    }
    
    public void Show_User_In_JTable(){
        ArrayList<User> list = getUserList();
        DefaultTableModel model = (DefaultTableModel) jTableuser.getModel();
        Object[] row = new Object[7];
        for(int i = 0;i < list.size();i++){
            row[0] = list.get(i).getNo();
            row[1] = list.get(i).getKodeBuku();
            row[2] = list.get(i).getBuku();
            row[3] = list.get(i).getTglPinjam();
            row[4] = list.get(i).getTglKembali();
            row[5] = list.get(i).getStatus();
            row[6] = list.get(i).getNis();
            model.addRow(row);
        }
    }
        public void executeSQlQuery(String query, String message){
            con = getConnection();
            Statement st;
            try{
                st = con.createStatement();
                if((st.executeUpdate(query)) == 1){
                    DefaultTableModel model = (DefaultTableModel) jTableuser.getModel();
                    model.setRowCount(0);
                    Show_User_In_JTable();
                    JOptionPane.showMessageDialog(null, "Data "+message+" Sukses");
                }else{
                    JOptionPane.showMessageDialog(null, "Data Not "+message);
                }
            }catch(Exception e){
                e.printStackTrace();
            }
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        insertDB = new javax.swing.JButton();
        updateDB = new javax.swing.JButton();
        deleteDB = new javax.swing.JButton();
        status = new javax.swing.JTextField();
        no = new javax.swing.JTextField();
        kode_buku = new javax.swing.JTextField();
        buku = new javax.swing.JTextField();
        tgl_pinjam = new javax.swing.JTextField();
        ss = new javax.swing.JLabel();
        tgl = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        as = new javax.swing.JLabel();
        tgl1 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        clear = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tgl2 = new javax.swing.JLabel();
        tgl_kembali = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        nis = new javax.swing.JTextField();
        asf = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabelClose = new javax.swing.JLabel();
        jLabelMin = new javax.swing.JLabel();
        status1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableuser = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(33, 12, 75));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(33, 12, 75));
        jButton1.setForeground(new java.awt.Color(254, 254, 254));
        jButton1.setText("Back");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 470, 90, 30));

        insertDB.setBackground(new java.awt.Color(33, 12, 75));
        insertDB.setForeground(new java.awt.Color(254, 254, 254));
        insertDB.setText("Insert");
        insertDB.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        insertDB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        insertDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertDBActionPerformed(evt);
            }
        });
        jPanel2.add(insertDB, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, 80, 30));

        updateDB.setBackground(new java.awt.Color(33, 12, 75));
        updateDB.setForeground(new java.awt.Color(254, 254, 254));
        updateDB.setText("Update");
        updateDB.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        updateDB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updateDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateDBActionPerformed(evt);
            }
        });
        jPanel2.add(updateDB, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 420, 80, 30));

        deleteDB.setBackground(new java.awt.Color(33, 12, 75));
        deleteDB.setForeground(new java.awt.Color(254, 254, 254));
        deleteDB.setText("Delete");
        deleteDB.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        deleteDB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteDBActionPerformed(evt);
            }
        });
        jPanel2.add(deleteDB, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 420, 80, 30));

        status.setBackground(new java.awt.Color(33, 12, 75));
        status.setForeground(new java.awt.Color(254, 247, 247));
        status.setBorder(null);
        status.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                statusMouseClicked(evt);
            }
        });
        jPanel2.add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 510, -1));

        no.setBackground(new java.awt.Color(33, 12, 75));
        no.setForeground(new java.awt.Color(254, 247, 247));
        no.setBorder(null);
        jPanel2.add(no, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 510, -1));

        kode_buku.setBackground(new java.awt.Color(33, 12, 75));
        kode_buku.setForeground(new java.awt.Color(254, 247, 247));
        kode_buku.setBorder(null);
        jPanel2.add(kode_buku, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 510, -1));

        buku.setBackground(new java.awt.Color(33, 12, 75));
        buku.setForeground(new java.awt.Color(254, 247, 247));
        buku.setBorder(null);
        jPanel2.add(buku, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 510, -1));

        tgl_pinjam.setBackground(new java.awt.Color(33, 12, 75));
        tgl_pinjam.setForeground(new java.awt.Color(254, 247, 247));
        tgl_pinjam.setBorder(null);
        jPanel2.add(tgl_pinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 510, -1));

        ss.setBackground(new java.awt.Color(254, 250, 247));
        ss.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        ss.setForeground(new java.awt.Color(255, 233, 233));
        ss.setText("Status");
        jPanel2.add(ss, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        tgl.setBackground(new java.awt.Color(254, 250, 247));
        tgl.setFont(new java.awt.Font("Waree", 1, 24)); // NOI18N
        tgl.setForeground(new java.awt.Color(255, 233, 233));
        jPanel2.add(tgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 160, 45));

        jLabel4.setBackground(new java.awt.Color(254, 250, 247));
        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 233, 233));
        jLabel4.setText("Kode Buku");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        as.setBackground(new java.awt.Color(254, 250, 247));
        as.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        as.setForeground(new java.awt.Color(255, 233, 233));
        as.setText("Buku");
        jPanel2.add(as, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        tgl1.setBackground(new java.awt.Color(254, 250, 247));
        tgl1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        tgl1.setForeground(new java.awt.Color(255, 233, 233));
        tgl1.setText("Tanggal Pinjam");
        jPanel2.add(tgl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 510, 10));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 510, 10));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 510, 10));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 510, 10));
        jPanel2.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 510, 10));

        clear.setBackground(new java.awt.Color(33, 12, 75));
        clear.setForeground(new java.awt.Color(254, 254, 254));
        clear.setText("Clear");
        clear.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        clear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel2.add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 420, 80, 30));

        jLabel8.setBackground(new java.awt.Color(254, 250, 247));
        jLabel8.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 233, 233));
        jLabel8.setText("No");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel9.setBackground(new java.awt.Color(254, 250, 247));
        jLabel9.setFont(new java.awt.Font("Waree", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 233, 233));
        jLabel9.setText("Tanggal :");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, -1, -1));

        tgl2.setBackground(new java.awt.Color(254, 250, 247));
        tgl2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        tgl2.setForeground(new java.awt.Color(255, 233, 233));
        tgl2.setText("Tanggal Kembali");
        jPanel2.add(tgl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        tgl_kembali.setBackground(new java.awt.Color(33, 12, 75));
        tgl_kembali.setForeground(new java.awt.Color(254, 247, 247));
        tgl_kembali.setBorder(null);
        tgl_kembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tgl_kembaliMouseClicked(evt);
            }
        });
        jPanel2.add(tgl_kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 510, -1));
        jPanel2.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 510, 10));

        nis.setBackground(new java.awt.Color(33, 12, 75));
        nis.setForeground(new java.awt.Color(254, 247, 247));
        nis.setBorder(null);
        nis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nisMouseClicked(evt);
            }
        });
        jPanel2.add(nis, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 510, -1));

        asf.setBackground(new java.awt.Color(254, 250, 247));
        asf.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        asf.setForeground(new java.awt.Color(255, 233, 233));
        asf.setText("NIS");
        jPanel2.add(asf, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));
        jPanel2.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 510, 10));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 40, 540, 510));

        jPanel1.setBackground(new java.awt.Color(137, 107, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelClose.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabelClose.setForeground(new java.awt.Color(255, 0, 0));
        jLabelClose.setText("X");
        jLabelClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 0, 20, 40));

        jLabelMin.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        jLabelMin.setText("-");
        jLabelMin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 0, 20, 40));

        status1.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        status1.setForeground(new java.awt.Color(255, 245, 245));
        status1.setText("Koneksi Database");
        status1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        status1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                status1MouseClicked(evt);
            }
        });
        jPanel1.add(status1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 100, 40));

        jLabel10.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(254, 254, 254));
        jLabel10.setText("Status : ");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 50, 40));

        jLabel6.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(254, 254, 254));
        jLabel6.setText("Peminjaman");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, -1, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, -1));

        jTableuser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Kode Buku", "Buku", "Tgl Pinjam", "Tgl Kembali", "Status", "Nis"
            }
        ));
        jTableuser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableuserMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableuser);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 520, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
        // TODO add your handling code here:
        System.exit(0); //Ini untuk Exit Aplikasi
    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void jLabelMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED); //Ini untuk Minimized Aplikasi
    }//GEN-LAST:event_jLabelMinMouseClicked

    private void status1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_status1MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Ini adalah status koneksi Database\nJika status anda Disconnected silahkan periksa port MySql atau aktifkan aplikasi MySql, Default port : 3306");
    }//GEN-LAST:event_status1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Menu menu = new Menu();
        menu.setVisible(true);
        menu.pack();
        menu.setLocationRelativeTo(null);
        menu.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void insertDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertDBActionPerformed
        // TODO add your handling code here:
        String query = "INSERT INTO `tb_peminjam`(`nama`, `jumlah_buku`, `nama_buku`, `tgl_pinjam`) VALUES ('" + kode_buku.getText() + "'," + buku.getText() + ",'" + tgl_pinjam.getText() + "','" + status.getText() + "')";
        executeSQlQuery(query, "Inserted");
    }//GEN-LAST:event_insertDBActionPerformed

    private void updateDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateDBActionPerformed
        // TODO add your handling code here:
        String query = "UPDATE `tb_peminjam` SET `nama`='" + kode_buku.getText() + "',`jumlah_buku`=" + buku.getText() + ",`nama_buku`='" + tgl_pinjam.getText() + "',`tgl_pinjam`='" + status.getText() + "' WHERE `id_peminjam`= " +no.getText();
        executeSQlQuery(query, "Updated");
    }//GEN-LAST:event_updateDBActionPerformed

    private void deleteDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteDBActionPerformed
        // TODO add your handling code here:
        String query = "DELETE FROM `tb_peminjam` WHERE `id_peminjam`= " + no.getText();
        executeSQlQuery(query, "Deleted");
    }//GEN-LAST:event_deleteDBActionPerformed

    private void jTableuserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableuserMouseClicked
        // TODO add your handling code here:
        int i = jTableuser.getSelectedRow();
        TableModel model = jTableuser.getModel();
        no.setText(model.getValueAt(i, 0).toString());
        kode_buku.setText(model.getValueAt(i, 1).toString());
        buku.setText(model.getValueAt(i, 2).toString());
        tgl_pinjam.setText(model.getValueAt(i, 3).toString());
        tgl_kembali.setText(model.getValueAt(i, 4).toString());
        status.setText(model.getValueAt(i, 5).toString());
        nis.setText(model.getValueAt(i, 6).toString());
    }//GEN-LAST:event_jTableuserMouseClicked

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        no.setText("");
        kode_buku.setText("");
        buku.setText("");
        tgl_pinjam.setText("");
        getCalender();
    }//GEN-LAST:event_clearActionPerformed

    private void statusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statusMouseClicked
        // TODO add your handling code here:
        getCalender();
    }//GEN-LAST:event_statusMouseClicked

    private void tgl_kembaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tgl_kembaliMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tgl_kembaliMouseClicked

    private void nisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nisMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_nisMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(peminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(peminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(peminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(peminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new peminjaman().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel as;
    private javax.swing.JLabel asf;
    private javax.swing.JTextField buku;
    private javax.swing.JButton clear;
    private javax.swing.JButton deleteDB;
    private javax.swing.JButton insertDB;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelMin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTable jTableuser;
    private javax.swing.JTextField kode_buku;
    private javax.swing.JTextField nis;
    private javax.swing.JTextField no;
    private javax.swing.JLabel ss;
    private javax.swing.JTextField status;
    private javax.swing.JLabel status1;
    private javax.swing.JLabel tgl;
    private javax.swing.JLabel tgl1;
    private javax.swing.JLabel tgl2;
    private javax.swing.JTextField tgl_kembali;
    private javax.swing.JTextField tgl_pinjam;
    private javax.swing.JButton updateDB;
    // End of variables declaration//GEN-END:variables

}
