/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;


import java.awt.*;
import javax.swing.*;
import java.sql.*;


/**
 *
 * @author linux
 */
public class loginform extends javax.swing.JFrame {
    private Connection con;
    private Statement st;
    private ResultSet rs;
    
    private void StatusDB(){
        try{
            Class.forName("com.mysql.jdbc.Driver"); //Mendaftarkan Driver
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_perpustakaan_ak", "root", ""); //Menghubungkan ke Database
            status1.setForeground(Color.green); //Mengatur Warna Font
            status1.setText("Connected"); //Mengatur isi dari variabel status1
        }catch(ClassNotFoundException | SQLException e){
            status1.setForeground(Color.red);
            status1.setText("Disconnected");
            JOptionPane.showMessageDialog(null, "ERORR\nAnda tidak terhubung ke Database, silahkan cek port MySql atau aktifkan aplikasi MySql.\nDefault port : 3306"); //Menampilkan Pesan
            System.exit(0); //Keluar dari Aplikasi
        }
    }
    private void LoginDB(){
        try{
            StatusDB();
            st = con.createStatement(); //Membuat Statement
            String sql = "SELECT * FROM tb_user WHERE username='" + ifrusername.getText() + "' AND password='" + String.valueOf(ifrpassword.getPassword()) + "'";
            rs = st.executeQuery(sql);
            if(rs.next()){
                if(ifrusername.getText().equals(rs.getString("username")) && String.valueOf(ifrpassword.getPassword()).equals(rs.getString("password"))){
                    JOptionPane.showMessageDialog(null, "Login Sukses");
                    Menu menu = new Menu();
                    menu.setVisible(true);
                    menu.pack();
                    menu.setLocationRelativeTo(null);
                    menu.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                    this.dispose();
                }
            }else{
                    JOptionPane.showMessageDialog(null, "Username atau Password salah");
            }
        }catch(SQLException | HeadlessException e) {
        }
    }
    /**
     * Creates new form loginform
     */
    public loginform() {
        initComponents();
        StatusDB(); //Memanggil Fungsi StatusDB
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelClose = new javax.swing.JLabel();
        jLabelMin = new javax.swing.JLabel();
        status1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ifrusername = new javax.swing.JTextField();
        ifrpassword = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        lg = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        ifrlogin = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(137, 107, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelClose.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabelClose.setForeground(new java.awt.Color(255, 0, 0));
        jLabelClose.setText("X");
        jLabelClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 0, 20, 40));

        jLabelMin.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        jLabelMin.setText("-");
        jLabelMin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 0, 20, 40));

        status1.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        status1.setForeground(new java.awt.Color(255, 245, 245));
        status1.setText("Koneksi Database");
        status1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        status1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                status1MouseClicked(evt);
            }
        });
        jPanel1.add(status1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 100, 40));

        jLabel10.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(254, 254, 254));
        jLabel10.setText("Status : ");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 50, 40));

        jLabel6.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(254, 254, 254));
        jLabel6.setText("Aplikasi Perpustakaan");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, -1, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, -1));

        jPanel2.setBackground(new java.awt.Color(33, 12, 75));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(254, 250, 247));
        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 233, 233));
        jLabel2.setText("Username");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jLabel3.setBackground(new java.awt.Color(254, 250, 247));
        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 233, 233));
        jLabel3.setText("Password");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        ifrusername.setBackground(new java.awt.Color(33, 12, 75));
        ifrusername.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        ifrusername.setForeground(new java.awt.Color(248, 246, 253));
        ifrusername.setText("Your Username");
        ifrusername.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ifrusername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ifrusernameMouseClicked(evt);
            }
        });
        ifrusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ifrusernameActionPerformed(evt);
            }
        });
        jPanel2.add(ifrusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 330, 20));

        ifrpassword.setBackground(new java.awt.Color(33, 12, 75));
        ifrpassword.setForeground(new java.awt.Color(255, 250, 250));
        ifrpassword.setText("Your Password");
        ifrpassword.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ifrpassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ifrpasswordMouseClicked(evt);
            }
        });
        jPanel2.add(ifrpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 330, -1));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 330, 20));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 110, 20));

        lg.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        lg.setForeground(new java.awt.Color(254, 254, 254));
        lg.setText("Login");
        jPanel2.add(lg, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 40));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 330, 20));

        ifrlogin.setBackground(new java.awt.Color(33, 12, 75));
        ifrlogin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        ifrlogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ifrlogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ifrloginMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ifrloginMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ifrloginMouseEntered(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(254, 254, 254));
        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(254, 254, 254));
        jLabel1.setText("Login");
        ifrlogin.add(jLabel1);

        jPanel2.add(ifrlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 80, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 370, 320));

        jPanel3.setBackground(new java.awt.Color(254, 254, 254));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/koneksi/aknela.png"))); // NOI18N
        jLabel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, 230));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 360, 320));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
        // TODO add your handling code here:
        System.exit(0); //Ini untuk Exit Aplikasi
    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void jLabelMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED); //Ini untuk Minimized Aplikasi
    }//GEN-LAST:event_jLabelMinMouseClicked

    private void ifrusernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ifrusernameMouseClicked
        // TODO add your handling code here:
        ifrusername.setText("");
    }//GEN-LAST:event_ifrusernameMouseClicked

    private void ifrpasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ifrpasswordMouseClicked
        // TODO add your handling code here:
        ifrpassword.setText("");
    }//GEN-LAST:event_ifrpasswordMouseClicked

    private void status1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_status1MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Ini adalah status koneksi Database\nJika status anda Disconnected silahkan periksa port MySql atau aktifkan aplikasi MySql, Default port : 3306");
    }//GEN-LAST:event_status1MouseClicked

    private void ifrusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ifrusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ifrusernameActionPerformed

    private void ifrloginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ifrloginMouseEntered
        // TODO add your handling code here:
        ifrlogin.setBackground(new Color(8,0,50));
    }//GEN-LAST:event_ifrloginMouseEntered

    private void ifrloginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ifrloginMouseExited
        // TODO add your handling code here:
        ifrlogin.setBackground(new Color(33,12,75));
    }//GEN-LAST:event_ifrloginMouseExited

    private void ifrloginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ifrloginMouseClicked
        // TODO add your handling code here:
        LoginDB();
    }//GEN-LAST:event_ifrloginMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ifrlogin;
    private javax.swing.JPasswordField ifrpassword;
    private javax.swing.JTextField ifrusername;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelMin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lg;
    private javax.swing.JLabel status1;
    // End of variables declaration//GEN-END:variables
}
